### ISSUE TITLE
Expose more control

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/rdf-dereference.js#1]
Some small useful features for this tool:

* Allow custom headers to be passed.
* Return the received headers.
* Return the used content type.
* Lenient-mode

This will require some additions to Comunica's RDF dereference bus.

**Comment by ktk** [comment]
I would say this is pretty much what https://github.com/rdfjs-base/fetch-lite provides. Also one of the reasons why I asked for Sink interface
