### ISSUE TITLE
Support for microdata?

### ISSUE THREAD

**Issue by angelo-v** [rubensworks/rdf-dereference.js#26]
Hi @rubensworks, are you planning to also support microdata? Would you appreciate a PR to add this? Or can you recommend another library to also get microdata from html?

**Comment by rubensworks** [comment]
Oh, I thought this was supported here already my bad.
I'll update the configs to enable it, should just take a minute...

**Comment by rubensworks** [comment]
Done in 1.8.0.

**Comment by angelo-v** [comment]
wow, that was fast, thank you so much
