### ISSUE TITLE
Fails to parse certain triples with JSON-LD

### ISSUE THREAD

**Issue by brechtvdv** [rubensworks/rdf-dereference.js#29]
This is probably an issue with the JSON-LD streaming parser, but I put the issue here for the reproducability.

I publish a LD document (https://lodi.ilabt.imec.be/coghent/dmg/objecten?generatedAtTime=2021-05-21T17:12:34.363Z)
that contains information about subject <https://stad.gent/id/mensgemaaktobject/dmg/530026423/2021-05-21T17:12:34.363Z> and contains a link to its Production activity:
![image](https://user-images.githubusercontent.com/6189968/119986194-d780c300-bfc3-11eb-8bd7-9d5a7f37eacf.png)

Following triple should be parsed:<https://stad.gent/id/mensgemaaktobject/dmg/530026423/2021-05-21T17:12:34.363Z> <http://www.cidoc-crm.org/cidoc-crm/P108i_was_produced_by> _:b0
In the JSON-LD playground, this works:
![image](https://user-images.githubusercontent.com/6189968/119986595-54ac3800-bfc4-11eb-90b6-d54ae0643490.png)

When I run rdf-dereference to use the RDF parser, I don't retrieve this triple:
```
rdf-dereference https://lodi.ilabt.imec.be/coghent/dmg/objecten?generatedAtTime=2021-05-21T17:12:34.363Z | grep "https://stad.gent/id/mensgemaaktobject/dmg/530026423/2021-05-21T17:12:34.363Z" | grep "produced"
```

**Comment by rubensworks** [comment]
Does it only occur when parsing this full document, or can it also be reproduced in a smaller subset of the document? (The latter would make debugging _a lot_ easier)

**Comment by brechtvdv** [comment]
I made a subset of the document here: https://brechtvdv.github.io/demo-data/example-production-oslo.jsonld

The triple that I see missing is: 
```
<https://stad.gent/id/mensgemaaktobject/dmg/530026423/2021-05-21T17:12:34.363Z> <http://www.cidoc-crm.org/cidoc-crm/P108i_was_produced_by> _:b0
```
