### ISSUE TITLE
Sink interface?

### ISSUE THREAD

**Issue by ktk** [rubensworks/rdf-dereference.js#3]
I wanted to try the parser for getting back embedded JSON-LD in a HTML webpage, as it's done for SEO all the time.

Now I'm a bit confused as I cannot find a Sink interface that I would need for that, as you did in any other parsers. Am I missing something here?

**Comment by rubensworks** [comment]
I assume you already have a stream and you want to import that?
This other tool may fit better for that purpose: https://github.com/rubensworks/rdf-parse.js
