### ISSUE TITLE
Unable to run README examples

### ISSUE THREAD

**Issue by saxomoose** [rubensworks/rdf-dereference.js#44]
Thank you for this library. I am new to the LOD landscape and am going through https://www.rubensworks.net/blog/2019/10/06/using-rdf-in-javascript/.

I am trying to run the examples in the README.

In particular:
```javascript
import rdfDereferencer from "rdf-dereference";
const { data } = await rdfDereferencer.dereference("http://dbpedia.org/page/12_Monkeys");
data
    .on("data", (quad) => console.log(quad))
    .on("error", (error) => console.error(error))
    .on("end", () => console.log("Done."));
```

I get a `TypeError: rdfDereferencer.dereference is not a function`.

Content of my package.json:
```json
{
  "type": "module",
  "dependencies": {
    "fs": "^0.0.1-security",
    "n3": "^1.17.0",
    "rdf-data-factory": "^1.1.2",
    "rdf-dereference": "^2.1.0"
  }
}
```

**Comment by saxomoose** [comment]
It works if I modify the code to:
```javascript
const { data } = await rdfDereferencer.default.dereference("http://dbpedia.org/page/12_Monkeys");
```
Don't know if this is intended behavior.

**Comment by rubensworks** [comment]
Ah yeah, that is needed since you have `"type": "module"` in your package.json. Default exports are handled differently there.
