### ISSUE TITLE
Question: dereference JSON-LD document without dereferencing its contexts?

### ISSUE THREAD

**Issue by sdevalk** [rubensworks/rdf-dereference.js#48]
I use this package - with great pleasure - to dereference IRIs of JSON-LD documents. However, I find the dereferencing to be a bit slow, e.g. when using [this IRI](https://iiif.bodleian.ox.ac.uk/iiif/manifest/8b768982-e29d-437c-8b57-911b0dbffb41.json).

I get the impression that this package not only dereferences the actual IRIs, but also the IRIs that are mentioned in the `@context`s of the JSON-LD documents. Is that correct? Or when looking at the sample IRI: does it request the `@context` IRIs, `http://iiif.io/api/presentation/2/context.json` and `http://iiif.io/api/image/2/context.json`? If so, is it possible to disable this?

**Comment by sdevalk** [comment]
Thanks for the clear explanation, @rubensworks - that makes sense.

Caching or prefetching the contexts sounds perfect. Do you know how I can use a customer document loader?

I use this package in a module of my own that mostly dereferences JSON-LD documents, and occasionally documents in other RDF serializations. Is there a way to pass a custom loader for JSON-LD documents that is ignored for e.g. Turtle or N-Triples documents?

**Comment by rubensworks** [comment]
> Caching or prefetching the contexts sounds perfect. Do you know how I can use a customer document loader?

@sdevalk I should probably document this at some point, but something like the following should work (untested):

```
dereference('http://...', { '@comunica/actor-rdf-parse-jsonld:documentLoader': new MyDocumentLoader() });
```
Where `MyDocumentLoader` implements https://github.com/rubensworks/jsonld-context-parser.js/blob/master/lib/IDocumentLoader.ts

**Comment by sdevalk** [comment]
@rubensworks Thanks for the pointer! 👍🏻
