### ISSUE TITLE
Work on local files with relative paths

### ISSUE THREAD

**Issue by RubenVerborgh** [rubensworks/rdf-dereference.js#7]
I'd like to pass the CLI interace a (possibly relative) path to a local HTML or RDF file.

**Comment by rubensworks** [comment]
Sure, should be possible to add.

Note to self: add [@comunica/actor-rdf-dereference-file](https://github.com/comunica/comunica/tree/master/packages/actor-rdf-dereference-file) to config.
Also, the API should only allow local file dereferencing when a certain flag is enabled.

**Comment by rubensworks** [comment]
Added in 1.4.0.

Things like this are now possible:
```
$ rdf-dereference ~/Downloads/data/dbpedia-1000.jsonld
```

**Comment by RubenVerborgh** [comment]
👌 thank you
